### PR TITLE
Applying unit test using jest library

### PR DESCRIPTION
**Pull request by ezraermy**
This is the sixth project of Microverse's second module, and I write unit tests for the To Do list application using jest library.

## Essential requirements:
- Use Html/CSS
- Use JavaScript ES6
- Make sure linter for free of errors.
- Using GitHub flow.
- Documented in a professional way.

### CODE REVIEW

**Comment by ezraermy** [comment]
Dear code reviewer,

I am dropping this text to let you know that I don't have a coding partner for this project. Kindly take this into consideration when you make a review. 

Thanks and regards.

**Review by Kamba56 — COMMENTED** [review]
Hi @ezraermy,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that **does not have commits from your coding partner.** Kindly add proof that you were allowed to work alone by student success to your pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ezraermy** [comment]
file:///home/ezra/Pictures/Screenshots/Screenshot%20from%202023-03-09%2000-06-57.png

Dear @Kamba56, You may not see my text above that show tells me I don't have a coding partner for this project. Please consider the above picture as a proof of for further processing of the review. Thanks.

**Comment by ezraermy** [comment]
file:///home/ezra/Pictures/Screenshots/Screenshot%20from%202023-03-09%2000-06-57.png

**Comment by ezraermy** [comment]
Screenshot from 2023-03-09 00-06-57

Dear @Kamba56, You may not see my text above that show informs I don't have a coding partner for this project. Please consider the above picture as a proof of for further processing of the review. Thanks.

**Review by KayLemba — APPROVED** [review]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @ezraermy      , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] linters are passing
- [x] Professional README 💯 
- [x] Tests are passing
 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



well-1

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

**Comment by Kamba56** [comment]
> Screenshot from 2023-03-09 00-06-57
> 
> Dear @Kamba56, You may not see my text above that show informs I don't have a coding partner for this project. Please consider the above picture as a proof of for further processing of the review. Thanks.

@ezraermy, I apologize for that, but kindly always add a proof even after writing it.

**Pull request merged**
